Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/corneto-lU1q7eKj-py3.11/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
c = CarnivalILP(beta_weight=0, disable_acyclicity=False)
P = c.build(G, dd)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[12], line 2[0m
[1;32m      1[0m c [38;5;241m=[39m CarnivalILP(beta_weight[38;5;241m=[39m[38;5;241m0[39m, disable_acyclicity[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[0;32m----> 2[0m P [38;5;241m=[39m [43mc[49m[38;5;241;43m.[39;49m[43mbuild[49m[43m([49m[43mG[49m[43m,[49m[43m [49m[43mdd[49m[43m)[49m

File [0;32m~/work/corneto/corneto/corneto/methods/future/method.py:109[0m, in [0;36mMethod.build[0;34m(self, graph, data)[0m
[1;32m    104[0m     [38;5;28mself[39m[38;5;241m.[39mproblem[38;5;241m.[39madd_objectives(
[1;32m    105[0m         [38;5;28mself[39m[38;5;241m.[39mproblem[38;5;241m.[39mexpr[newvar_name][38;5;241m.[39msum(),
[1;32m    106[0m         weights[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mlambda_reg_param,
[1;32m    107[0m     )
[1;32m    108[0m [38;5;28;01melse[39;00m:
[0;32m--> 109[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    110[0m         [38;5;124m"[39m[38;5;124mParameter lambda_reg > 0 but no regularization variable name provided[39m[38;5;124m"[39m
[1;32m    111[0m     )
[1;32m    112[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mproblem

[0;31mValueError[0m: Parameter lambda_reg > 0 but no regularization variable name provided

